### ISSUE TITLE
ModuleNotFoundError: No module named 'duckietown_world'

### ISSUE THREAD

**Issue by SHITIANYU-hue** [rizavelioglu/challenge-aido_RL-IL#7]
When i run:
python log.py 
I got this error:
Traceback (most recent call last):
  File "log.py", line 7, in <module>
    from duckietown_rl.gym_duckietown.simulator import Simulator
  File "../duckietown_rl/gym_duckietown/simulator.py", line 10, in <module>
    from duckietown_world.world_duckietown.pwm_dynamics import get_DB18_nominal, get_DB18_uncalibrated
ModuleNotFoundError: No module named 'duckietown_world'

**Comment by rizavelioglu** [comment]
Hi Shitianyu,

As the error says, you are lacking the module "_duckietown_world_" and you can resolve the issue by installing that module.

I assume you are executing the code on your local PC, cause there is no such error when executing the code on [Colab](https://colab.research.google.com/drive/1zh3bKPrbMA4UmGqwe6OsT1wXDZ193xqS?usp=sharing). You might want to install the packages the way they are installed on Colab. But, one might install "_duckietown_world_" module with the following code:

`pip install duckietown-world`

The code on Colab does not actually install "_duckietown-world_" but another version of it which is specifically built for the "_daffy_" branch of "_gym-duckietown_" module ([See here](https://github.com/duckietown/gym-duckietown/tree/daffy)). And it's installed with the following code:

`pip install duckietown-world-daffy==5.1.2`

**Comment by SHITIANYU-hue** [comment]
Thanks for your reply! It works now!👍
